spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-plain-field-aqbkfzzl-pooler.c-8.us-east-1.aws.neon.tech/leetcode_tracker?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BcLtqNXoTh71

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080